services:
  backend:
    build: .
    container_name: backend_application
    ports:
        - 3001:3001
        - 5555:5555
    env_file:
        - .env

  migrate:
    build: .
    env_file:
      - .env
    command: ["npm", "run", "db:deploy"]