services:
  backend:
    image: "arnabpal342002/ai-finance-backend-application"
    container_name: backend_application
    ports:
        - 3001:3001
        - 5555:5555
    env_file:
        - .env

  migrate:
    image: "arnabpal342002/ai-finance-backend-application"
    env_file:
      - .env
    command: ["npm", "run", "db:deploy"]