export const locations = [
    'India',
    'Scotland',
    'China',
    'United States',
    'Indonesia',
    'Pakistan',
    'Brazil',
    'Nigeria',
    'Bangladesh',
    'Russia',
    'Mexico',
    'Japan',
    'Philippines',
    'Vietnam',
    'Germany',
    'Egypt',
    'Iran',
    'Turkey',
    'Congo',
    'France',
    'United Kingdom'
];