name: Build succeeds on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Install backend dependencies
        working-directory: backendNode
        run: npm install
      
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Generate Prisma client for backend
        working-directory: backendNode
        run: npm run db:generate
      
      - name: Build backend
        working-directory: backendNode
        run: npm run build
