name: Build and deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Need to add to github action
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./backendNode
        file: ./backendNode/Dockerfile
        push: true
        tags: arnabpal342002/ai-finance-backend-application:latest

    - name: Verify Pushed Image
      run: docker pull arnabpal342002/ai-finance-backend-application:latest

    - name: Copy docker-compose.yml to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "backendNode/docker-compose.yaml"
        target: "/home/ubuntu/backend"

    - name: Deplot to EC2
      uses: appleboy/ssh-action@master # Master specifies the version
      with:
        host: ${{ secrets.SSH_HOST }} # Need to add to github action
        username: ${{ secrets.SSH_USERNAME }} # Need to add to github action
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /backend/backendNode
          pwd
          ls
          docker-compose down
          docker-compose pull
          docker-compose up -d
