name: Build and deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Need to add to github action
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ../../backendNode
        file: ./Dockerfile
        push: true
        tags: arnabpal342002/ai-finance-application:latest

    - name: Verify Pushed Image
      run: docker pull arnabpal342002/ai-finance-application:latest